#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

import torch
from ultralytics import YOLO


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fine-tune the PlateBlur detector on PP4AV tiled road-scene data, then export and compile a Core ML bundle."
    )
    parser.add_argument(
        "--weights",
        default="/Users/applemima111/Desktop/car/models/koushim/best.pt",
        help="Base YOLO weights to fine-tune.",
    )
    parser.add_argument(
        "--data",
        default="/Users/applemima111/Desktop/car/train_data/pp4av_tiled_plate_dataset/plate_dataset.yaml",
        help="YOLO dataset YAML generated by prepare_pp4av_plate_dataset.py.",
    )
    parser.add_argument(
        "--project",
        default="/Users/applemima111/Desktop/car/models/plateblur_training",
        help="Ultralytics project directory.",
    )
    parser.add_argument(
        "--name",
        default="pp4av_tiled_small_object",
        help="Ultralytics run name.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=24,
        help="Number of fine-tuning epochs.",
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=640,
        help="Training image size.",
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=16,
        help="Training batch size.",
    )
    parser.add_argument(
        "--patience",
        type=int,
        default=8,
        help="Early-stopping patience.",
    )
    parser.add_argument(
        "--device",
        default="auto",
        help="Training device: auto, mps, cpu, or a CUDA device string.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=0,
        help="Data-loader workers. 0 is more reliable on macOS.",
    )
    parser.add_argument(
        "--developer-dir",
        default="/Applications/Xcode.app/Contents/Developer",
        help="Xcode developer directory used by coremlcompiler.",
    )
    parser.add_argument(
        "--app-model-dir",
        default="/Users/applemima111/Desktop/car/PlateBlur/PlateBlur",
        help="Where to copy the compiled LicensePlateDetector.mlmodelc bundle.",
    )
    parser.add_argument(
        "--export-name",
        default="LicensePlateDetector",
        help="Compiled Core ML bundle name copied into the app.",
    )
    return parser.parse_args()


def resolve_device(device: str) -> str:
    if device != "auto":
        return device
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def compile_mlpackage(mlpackage_path: Path, output_dir: Path, developer_dir: str, export_name: str) -> Path:
    build_dir = output_dir / ".coreml-build"
    shutil.rmtree(build_dir, ignore_errors=True)
    build_dir.mkdir(parents=True, exist_ok=True)

    env = {**os.environ, "DEVELOPER_DIR": developer_dir}
    subprocess.run(
        ["xcrun", "coremlcompiler", "compile", str(mlpackage_path), str(build_dir)],
        check=True,
        env=env,
    )

    compiled = build_dir / f"{mlpackage_path.stem}.mlmodelc"
    target = output_dir / f"{export_name}.mlmodelc"
    shutil.rmtree(target, ignore_errors=True)
    shutil.move(str(compiled), str(target))
    shutil.rmtree(build_dir, ignore_errors=True)
    return target


def main() -> None:
    args = parse_args()
    device = resolve_device(args.device)
    run_root = Path(args.project)
    run_root.mkdir(parents=True, exist_ok=True)

    model = YOLO(args.weights)
    results = model.train(
        data=args.data,
        project=str(run_root),
        name=args.name,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        patience=args.patience,
        device=device,
        workers=args.workers,
        optimizer="AdamW",
        lr0=1e-3,
        lrf=0.05,
        degrees=0.0,
        translate=0.05,
        scale=0.50,
        shear=0.0,
        perspective=0.0,
        fliplr=0.0,
        flipud=0.0,
        mosaic=0.70,
        mixup=0.0,
        copy_paste=0.0,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        close_mosaic=6,
        deterministic=True,
        pretrained=True,
    )

    save_dir = Path(results.save_dir)
    best_weights = save_dir / "weights" / "best.pt"
    export_model = YOLO(str(best_weights))
    mlpackage_path = Path(
        export_model.export(
            format="coreml",
            imgsz=args.imgsz,
            nms=True,
            half=False,
            int8=False,
        )
    )

    app_model_dir = Path(args.app_model_dir)
    app_model_dir.mkdir(parents=True, exist_ok=True)
    compiled_path = compile_mlpackage(
        mlpackage_path=mlpackage_path,
        output_dir=app_model_dir,
        developer_dir=args.developer_dir,
        export_name=args.export_name,
    )

    payload = {
        "device": device,
        "save_dir": str(save_dir),
        "best_weights": str(best_weights),
        "mlpackage": str(mlpackage_path),
        "compiled_model": str(compiled_path),
    }
    (save_dir / "plateblur_export_summary.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
